digraph G {
n2[label="all", color="red"];
n6[label="data/chopstick.csv", color="green"];
n3[label="doc/chopstick_analysis.md", color="green"];
n4[label="results/figure/eff_individual.png", color="green"];
n8[label="results/figure/eff_length.png", color="green"];
n9[label="results/model.csv", color="green"];
n7[label="src/download_data.R", color="green"];
n10[label="src/linear_model.R", color="green"];
n5[label="src/plot.R", color="green"];
n3 -> n2 ; 
n7 -> n6 ; 
n4 -> n3 ; 
n8 -> n3 ; 
n9 -> n3 ; 
n6 -> n4 ; 
n5 -> n4 ; 
n6 -> n8 ; 
n5 -> n8 ; 
n6 -> n9 ; 
n10 -> n9 ; 
}
